
networks:
  flooke-network:

services:

  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    # network_mode: host
    networks:
      - flooke-network
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  flooke_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: flooke_server
    command: python manage.py runserver 0.0.0.0:8080
    hostname: flooke_server
    image: flooke-server-image
    # network_mode: host
    networks:
      flooke-network:
    ports:
      - 8080:8080
    depends_on:
      # - flooke_db
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION: 'eu-west-1'
    env_file:
      - server/.env
