# Set Python runtime as a parent image
FROM public.ecr.aws/lambda/python:3.12

# Copy the codebase in /application_functions into the container at /$(LAMBDA_TASK_ROOT)
# This will also copy the requirements.txt file into the container
ADD . .

# Install the dependencies for production
RUN pip3 install -r requirements.txt

CMD ["lambda_handler.lambda_handler"]
