# Generated by Django 5.1 on 2024-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emoji_unicode',
            field=models.CharField(null=True),
        ),
    ]
