# Generated by Django 4.2 on 2024-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_comment_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
    ]
