# Generated by Django 4.2 on 2024-09-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_has_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_reply',
        ),
    ]
